language: php
php:
  - '5.6'
  # - hhvm # on Trusty only
  # - nightly

before_script: 
  - composer require phpunit/phpunit 5.7

script: 
  - vendor/bin/phpunit --coverage-clover=coverage.xml tests

after_success:
  - bash <(curl -s https://codecov.io/bash)